package:
  name: pirate
  version: "prerelease" ## add version with github release

source:
   git_rev: # add when release versions updated
   git_url: https://github.com/SionBayliss/PIRATE.git 

build:
  number: 1

requirements:
  build:
    - mcl >=14.137
    - mafft ==7.310
    - cd-hit >=4.6.4
    - fasttree >=2.1.10
    - diamond >=0.9.14
    - blast >=2.2.31
    - perl-bioperl ==1.6.924
    - parallel >=20170422

  run:
    - mcl >=14.137
    - mafft ==7.310
    - cd-hit >=4.6.4
    - fasttree >=2.1.10
    - diamond >=0.9.14
    - blast >=2.2.31
    - perl-bioperl ==1.6.924
    - parallel >=20170422

test:
  imports:
   
  commands:
    - PIRATE --check
about:
  home: https://github.com/SionBayliss/PIRATE
  license: GPLv2
  summary: "Pre-release PIRATE - a pangenome construction and threshold evaluation tool for multiple genomic features."
