package:
  name: pirate
  version: "prerelease" ## add version with github release

source:
   git_rev: # add when release versions updated
   git_url: https://github.com/SionBayliss/PIRATE.git 

build:
  number: 1

requirements:
  build:
    - perl-bioperl ==1.7.2
    - mcl >=14.137
    - mafft ==7.310
    - cd-hit >=4.6.4
    - fasttree >=2.1.10
    - diamond >=0.9.14
    - blast >=2.2.31
    - parallel >=20170422

  run:
    - perl-bioperl ==1.7.2
    - mcl >=14.137
    - mafft ==7.310
    - cd-hit >=4.6.4
    - fasttree >=2.1.10
    - diamond >=0.9.14
    - blast >=2.2.31
    - parallel >=20170422

test:
  imports:
   
  commands:
#    - PIRATE --check
about:
  home: https://github.com/SionBayliss/PIRATE
  license: GPL3
  license_file: LICENSE
  summary: "PIRATE (pre-release) - a pangenomics toolbox"
